namespace Internship_7_Library.Data.Enums
{
    public enum Grade
    {
        FirstA,
        FirstB,
        FirstC,
        SecondA,
        SecondB,
        SecondC,
        ThirdA,
        ThirdB,
        ThirdC,
        FourthA,
        FourthB,
        FourthC,
        FifthA,
        FifthB,
        FifthC,
        SixthA,
        SixthB,
        SixthC,
        SeventhA,
        SeventhB,
        SeventhC,
        EighthA,
        EighthB,
        EighthC
    }
}
